<p>
    Create a Request to Purchase Project 
</p>

<section>
    <h3>Project Title</h3>

    <p>
        Brief description of the work being done for the college. Title will show up
        in lists and emails generated by TREQ. For example:
    </p>

    <ul>
        <li>Travel to AERA</li>
        <li>Recruiting Event</li>
        <li>Smith / NSF Research</li>
        <li>Training Seminar, Professional Development</li>
    </ul>
</section>

<section>
    <h3>Project Owner</h3>

    <p>
        Generally this is you. If you are entering an order on behalf of someone else and
        they are the one who should contacted with questions, change this to another UAA
        person.
    </p>
</section>

<section>
    <h3>Business Purpose</h3>

    <p>
        UW defines business purpose as: "Explanation of how the purchase or payment is used
        for UW business." In addition, all expenditures on grants are required to have an
        additional statement on the expenditure's benefit to grant. For example:
    </p>

    <ul>
        <li>Purchase of SOMETHING for use in the PROGRAM_NAME program.</li>
        <li>Purchase of books for use in PROGRAM_NAME program</li>
        <li>Purchase of food for in-person new student orientation on EVENT_DATE.</li>
        <li>Transcription services for interviews performed on WORK_DATE for NAME_OF_GRANT research project</li>
        <li>To attend and present paper at AERA Annual Conference</li>
    </ul>
</section>
