<?php
namespace App\Workflows\TaskSteps;

/**
 * OptionalStageSteps represent stages not in a standard Workflow.
 *
 * Order workflow can be manually changed by users requesting extra Approvals
 * or adding extra Tasks. OptionalStageSteps detect those extra Task records
 * and label the Order with the appropriate stage.
 *
 * Examples: NeedsApproval, PendingTask, Resubmitted
 *
 * To implement an OptionalStageStep just provide the public properties
 * $stage and $taskType.
 */
class OptionalStageStep extends TaskStep
{
    public $hasTask = true;

    /**
     * These are optional stages, only created by user interaction with the system.
     * They will never be generated by the workflow system, so activate() can
     * safely do nothing.
     */
    public function activate(): void
    {
        // do nothing
    }

    public function isComplete(): bool
    {
        return ! $this->hasIncompleteTasks($this->taskType);
    }
}
