{!! $intro !!}

=========================================================
{!! $projectNumber !!}
{!! $projectTitle !!}
{!! $type !!}
Submitted {!! $submitted !!}
=========================================================

View this order here:

{!! $url !!}


------------

This email notification was generated by the University of Washington, College
of the Environment's {!! $appName !!}. If you have trouble with this
notification or have received this message in error, please contact the college
Help Desk at envithelp@uw.edu.
