{!! $intro !!}

=========================================================
{!! $projectNumber !!}
{!! $projectTitle !!}
{!! $type !!}
Submitted {!! $submitted !!}
=========================================================

View this order here:

{!! $url !!}


------------

This email notification was generated by the University of Washington, Information School's {!! $appName !!}. If you have trouble with this
notification or have received this message in error, please contact UWORG at uworgtreq@uw.edu.
