{!! $intro !!}

=========================================================
{!! $projectNumber !!}
{!! $projectTitle !!}
{!! $type !!}
Submitted {!! $submitted !!}
=========================================================

View this order here:

{!! $url !!}


------------

This email notification was generated by the {!! config('custom.scl_long') !!}'s {!! $appName !!}. If you have trouble with this
notification or have received this message in error, please contact the college
Finance Department at {!! config('custom.scl_email_treq') !!}.
