<?php

$filename = 'treq_'.date('Y-m-d').'.csv';

header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Expires: 0');
header('Pragma: public');
header('Content-type: text/csv');
header('Content-Disposition: attachment; filename='.$filename);

echoCsvRow([
    'ID',
    'Project ID',
    'Type',
    'Stage',
    'submitted_at',
    'submitted_by',
    'amount',
    'active_at',
    'notified_at',
    'assigned_to',
    'on_call',
    'created_at',
    'updated_at',
    'Project ID',
    'Project Title',
    'Project person Id',
    'Project Purpose ',
    'Project Is travel ',
    'Project Is Food ',
    'Project Is gift card ',
    'Project Is RSP',
    'Project folder url',
    'Project Folder name',
    'Project Folder deleted',
    'Project Closed at',
    'Project Closed by ',
    'Project Created at',
    'Project updated at',
    'Submitter uwnetid',
    'Submitter person id ',
    'Submitter first name',
    'Submitter last name',
    'Submitter student no ',
    'Submitter employee id ',
    'Submitter email ',
    'Submitter Created at',
    'Submitter Updated at',
    'Tracking id',
    'Tracking Order Id',
    'Tracking Last action',
    'Tracking Last Actor',
    'Tracking Last at',
    'Tracking Next action',
    'Tracking Next actors',
    'Tracking Created at',
    'Tracking Updated at',

]);

foreach ($reportdata as $order) {
    echoCsvRow([
        // $order->id,
        // $order->project_id,
        // $order->type,
        // $order->stage,
        // $order->submitted_at?? '',
        // $order->submitted_by,
        // $order->amount?? '',
        // $order->active_at?? '',
        // $order->notified_at?? '',
        // $order->assigned_to?? '',
        // $order->on_call?? '',
        // $order->created_at,
        // $order->updated_at,
        // $order->project?->id,
        // $order->project?->title,
        // $order->project?->person_id,
        // $order->project?->purpose,
        // $order->project?->is_travel,
        // $order->project?->is_food,
        // $order->project?->is_gift_card,
        // $order->project?->is_rsp,
        // $order->project?->folder_url,
        // $order->project?->folder_name,
        // $order->project?->folder_deleted,
        // $order->project?->closed_at,
        // $order->project?->closed_by,
        // $order->project?->created_at,
        // $order->project?->updated_at,
        // $order->submitter?->uwnetid,
        // $order->submitter?->person_id,
        // $order->submitter?->firstname,
        // $order->submitter?->lastname,
        // $order->submitter?->studentno,
        // $order->submitter?->employeeid,
        // $order->submitter?->email,
        // $order->submitter?->created_at,
        // $order->submitter?->updated_at,
        // $order->tracking?->id,
        // $order->tracking?->order_id,
        // $order->tracking?->last_action,
        // $order->tracking?->last_actor,
        // $order->tracking?->last_at,
        // $order->tracking?->next_action,
        // $order->tracking?->next_actors,
        // $order->tracking?->created_at,
        // $order->tracking?->updated_at
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,
        $order->id,

    ]);
}
