<?php

$filename = 'treq_'.date('Y-m-d').'.csv';

header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Expires: 0');
header('Pragma: public');
header('Content-type: text/csv');
header('Content-Disposition: attachment; filename='.$filename);

echoCsvRow([
    'Task ID',
    'Task Order ID',
    'Task type',
    'Task name',
    'Sequence',
    'Is approval',
    'Budget Number',
    'Description',
    'Created by',
    'Assigned to',
    'Notified at',
    'Response',
    'Message',
    'Completed by',
    'Completed at',
    'Created at',
    'Updated at',
    'Order ID',
    'Order Project ID',
    'Order Type',
    'Order Stage',
    'Order submitted_at',
    'Order submitted_by',
    'Order amount',
    'Order active_at',
    'Order notified_at',
    'Order assigned_to',
    'Order on_call',
    'Order created_at',
    'Order updated_at',    
    'Project ID',
    'Project Title',
    'Project person Id',
    'Project Purpose ',
    'Project Is travel ',
    'Project Is Food ',
    'Project Is gift card ',
    'Project Is RSP',
    'Project folder url',
    'Project Folder name',
    'Project Folder deleted',
    'Project Closed at',
    'Project Closed by ',
    'Project Created at',
    'Project updated at',

]);

foreach ($reportdata as $task) {
    echoCsvRow([
        $task->id,
        $task->order_id,
        $task->type,
        $task->name,
        $task->sequence,
        $task->is_approval,
        $task->budgetno,
        $task->description,
        $task->created_by,
        $task->assigned_to,
        $task->notified_at,
        $task->response,
        $task->message,
        $task->completed_by,
        $task->completed_at,
        $task->created_at,
        $task->updated_at,
        $task->order?->id,
        $task->order?->project_id,
        $task->order?->type,
        $task->order?->stage,
        $task->order?->submitted_at,
        $task->order?->submitted_by,
        $task->order?->amount,
        $task->order?->active_at,
        $task->order?->notified_at,
        $task->order?->assigned_to,
        $task->order?->on_call,
        $task->order?->created_at,
        $task->order?->updated_at,
        $task->order?->project?->id,
        $task->order?->project?->title,
        $task->order?->project?->person_id,
        $task->order?->project?->purpose,
        $task->order?->project?->is_travel,
        $task->order?->project?->is_food,
        $task->order?->project?->is_gift_card,
        $task->order?->project?->is_rsp,
        $task->order?->project?->folder_url,
        $task->order?->project?->folder_name,
        $task->order?->project?->folder_deleted,
        $task->order?->project?->closed_at,
        $task->order?->project?->closed_by,
        $task->order?->project?->created_at,
        $task->order?->project?->updated_at

    ]);
}
